name: travelly
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  google_maps_flutter: ^2.9.0
  image_picker: ^0.8.5+3
  flutter:
    sdk: flutter
  provider: ^6.0.0


  sqflite: ^2.0.0+4
  path: ^1.8.0


  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1   
  cloud_firestore: ^5.4.4  
  firebase_storage: ^12.3.4  
  syncfusion_flutter_charts: ^20.2.45
  table_calendar: ^3.1.2
  flutter_local_notifications: ^18.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_dotenv: ^5.2.1
  flutter_map_marker_cluster: ^1.4.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and list assets as needed
  assets:
  
    - .mapkey.env

    - lib/assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700